### ISSUE TITLE
Reconnect to GeigerToolbox after disconnecting

### ISSUE THREAD

**Issue by luongnv89** [cyber-geiger/toolbox-communicationApi#11]
**Describe the problem**
An external plugin cannot reconnect to the GeigerToolbox after disconnecting

Need some instruction on `How to close a GeigerAPI properly so that it can be re-connected after disconnecting from GeigerToolbox`?

**Environmental information**
- Development environment: MacOS Montery 12.1 x VS Studio Code
- Testing environment: Android Emulator Google Pixel XL API 30
- Flutter: 2.8.1
- geiger_api: 0.6.2

**To Reproduce**
- Start the GeigerToolbox app, make sure it is ready for connecting
- Start the External Plugin app-> register & activate => OK
- Test a basic function: get currentUserId => OK
- Disconnect the external plugin (by closing the external app)
- Re-open the External plugin app -> register & activate => OK
- Test a basic function: get currentUserId => Failed
**Expected behavior**
The second test failed due to a socket error
```sh
E[/flutter]() (26964): [ERROR:flutter[/lib/ui/ui_dart_state.cc]()(209)] Unhandled Exception: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 42070
```

**Screenshots**
Error log
![Screen Shot 2022-02-03 at 14 45 32](https://user-images.githubusercontent.com/3288457/152354794-ff95782a-a3ee-4e32-aba5-97cb993c0816.png)

**Additional context**
When closing an external plugin, these following steps have been executed:
```dart
if (pluginApi != null) {
      if (storageController != null) {
        // Unregister all the listener
        if (storageListener != null) {
          log('[close] Going to deregister all the change listeners');
          try {
            await storageController!.deregisterChangeListener(storageListener!);
            log('[close] All the change listeners have been removed');
          } catch (e) {
            log('[close] Failed to deregister the storage listener');
            log(e.toString());
          }
        }
        //close the storage controller
        // log('[close] Going to close the storage controller');
        // try {
        //   await storageController!.close();
        //   log('[close] The storage controller has been closed');
        // } catch (e) {
        //   log('[close] Failed to close the storage controller');
        //   log(e.toString());
        // }
        storageController = null;
        storageListener = null;
      }
      log('[close] Going to close the geiger api');
      try {
        await pluginApi!.zapState();
        await pluginApi!.close();
        pluginListener = null;
        log('[close] The GeigerAPI has been closed');
      } catch (e) {
        log('[close] Failed to close the GeigerAPI');
        log(e.toString());
      }
    }
```

Note that, if the line `await storageController!.close();` is executed, there will be error saying that the database has been closed already.

**Comment by tschai-yim** [comment]
This issue was likely because the master did not use the new port from the `registerPlugin` call when the plugin is already known. As that issue has been fixed, could you retest your scenario again?

**Comment by luongnv89** [comment]
@tschai-yim has the fixing been added in the latest version of the `geiger_api: 0.7.2 (5 days ago)`? Thanks

**Comment by tschai-yim** [comment]
Sorry no. You'll have to clone the repo and change your pubspec to the following:
```yml
dependencies:
  geiger_api:
    path: path/to/cloned/repo
```

**Comment by luongnv89** [comment]
and which branch should I test? `development`?

**Comment by tschai-yim** [comment]
yes

**Comment by luongnv89** [comment]
I can confirm that an external plugin can reconnect to the toolbox, but only if we close (quit) completely the external plugin. 
If the external plugin disconnect manually (via the above steps), then try to reconnect with the toolbox, the problem is still persist.
In any case, the scenario where a user want to disconnect (manually) then reconnect with the toolbox is unlikely to be happen, so I would say that the issue can be closed here (and will be re-opened in the future if needed).
Many thanks for your support @tschai-yim
