### ISSUE TITLE
External plugin on Samsung galaxy s21 not connecting

### ISSUE THREAD

**Issue by BananaEgg** [cyber-geiger/toolbox-communicationApi#12]
I've tested both my plugin and the one developed by @luongnv89 on a Samsung galaxy s21, both cannot establish a connection with the toolbox.
The issue accrues only in release mode so I cannot provide any error message.
(I need to figure out how to setup logging on release mode)

Edit:
The issue might not be with Samsung, but with the android version the Samsung is android 12, and the other device that worked was android 10.

**Comment by nosadaniel** [comment]
FYI: the android studio has the functionality to help you test your app(flutter) on release mode and see the log, provided you are using a real device.

**Comment by BananaEgg** [comment]
> 



> FYI: the android studio has the functionality to help you test your app(flutter) on release mode and see the log, provided you are using a real device.

Thank you, Ill check that out.

**Comment by BananaEgg** [comment]
It's working now, not sure what was the issue.
closing issue.
