### ISSUE TITLE
External plugins do not create databbase change events in the environment of the master (toolbox core)

### ISSUE THREAD

**Issue by martingwerder** [cyber-geiger/toolbox-communicationApi#14]
Describe the bug
===
When an external plugin issues a change on the localstorage database, the change generates a storage listener event in the plugin but not on the master.

Environmental information
===
- Platform: Windows X
- Flutter: 2.10.1
- involved components: geiger_localstorage
- problematic component: passthrough_controller?

To Reproduce
===
I will add unit tests to repoduce the issue.

Expected behavior
===
All changes on the database should always cause events on all components (plugins and cores).

Screenshots
===
none

Additional context
===
This is an internal issue to flag the presence of this bug and make it public.

**Comment by tschai-yim** [comment]
I added a test (https://github.com/cyber-geiger/toolbox-communicationApi/commit/899ee1cf66c564dcc7cf8fac7c04bc537b98f47c) for this issue but was not able to reproduce the issue. As all change events are handled by the master this seems rather strange.

**Comment by martingwerder** [comment]
Closed as no one can confirm or denie this issue.
