### ISSUE TITLE
How to authorise an external plugin base on event received.

### ISSUE THREAD

**Issue by nosadaniel** [cyber-geiger/toolbox-communicationApi#17]
How to authorize an external plugin from the UI side base on event received.

**Comment by tschai-yim** [comment]
Could you provide more detail about your issue?
Like:
- What do you mean by authorizing? Nothing requires authorization currently.
- Is there a problem with using Geiger API specifically in UI-related code?

**Comment by nosadaniel** [comment]
The UI has this scenario where an external plugin sends an event to the UI, it has to either deny or authorize the plugin... so I found this method ```authorizePlugin(plugin) ``` in the GeigerApi abstract class.

anyway...thanks for the clarification, I thought authorization was needed

Thanks

**Comment by tschai-yim** [comment]
The authorization will be needed later when it gets implemented. 
I'll close this issue because for now plugins are automatically authorized.
