### ISSUE TITLE
Returning control is not possible in geiger_api:0.7.3

### ISSUE THREAD

**Issue by luongnv89** [cyber-geiger/toolbox-communicationApi#20]
In the `geiger_api version 0.7.3`, the field `GeigerApi.masterExecutor` is still a constant (image bellow), theforce it cannot be changed as in the `client_app` example. 
<img width="696" alt="Screen Shot 2022-03-31 at 00 03 39" src="https://user-images.githubusercontent.com/3288457/160938973-5d13380e-903a-41ab-81b2-a1351209c487.png">
=> which means that to be able to implement the "returning control" now, once has to use the `geiger_api` with a specific dependencies declaration (either via git or local repository)

Is there a new version going out soon with this update?

**Comment by tschai-yim** [comment]
As you probably noticed, this is fixed in the latest [`development`](https://github.com/cyber-geiger/toolbox-communicationApi/blob/development/lib/src/geiger_api.dart#L15=) version. Martin will be releasing it asap.

**Comment by luongnv89** [comment]
Thanks @tschai-yim . I am waiting for a new release ...

**Comment by martingwerder** [comment]
Published as 0.7.4

Can you confirm that the issue is resolved?

**Comment by luongnv89** [comment]
I can confirm that the problem has been resolved with the latest version of geiger api: 0.7.4
Many thanks to your team @martingwerder
