### ISSUE TITLE
abstract class of PluginListener not exposed

### ISSUE THREAD

**Issue by nosadaniel** [cyber-geiger/toolbox-communicationApi#3]
Description:
I was trying to implement PluginListener as demonstrated in the test of external_communication_test.dart of the geigerApi,  but the PluginListener abstract class seem not to exist.

Upon forward investigation, I found out plugin_listener.dart was not exported.

**Comment by martingwerder** [comment]
Thanks for that one should be fixed now. Is published as new development release 0.5.2 on pub.dev
