### ISSUE TITLE
Returning control to an external plugin which has been closed

### ISSUE THREAD

**Issue by luongnv89** [cyber-geiger/toolbox-communicationApi#32]
Describe the bug
===
The external plugin cannot open the specific screen which sent in the returning control message from the toolbox.

Environmental information
===
- Android
- geiger_api: 0.7.9

To Reproduce
===

1. Install and open the Toolbox
2. Install and open an external plugin, the external plugin should have a specific page X which is not the default page when open the app.
3. Connect the external plugin with the Toolbox
4. From the Toolbox, send a returning control to go to a specific page X on the external plugin => It worked
5. Close the external plugin
6. Repeat the step 4 => The external plugin will be reopened, but it cannot not go to the page X (it only goes to the default page)

**Comment by JonasDev17** [comment]
Tested on the official client / master example app. 
Both, payload and geiger url arrive on the client app.

**Comment by tschai-yim** [comment]
Double checked and the full message successfully arrives using the official Dart example when called in the background and foreground. Could you please provide an MRE?

**Comment by luongnv89** [comment]
> Tested on the official client / master example app. Both, payload and geiger url arrive on the client app.

- Did you check with the client app is off (not running in the background, but turn off completely)?
- And also, the payload and the geiger url can arrive on the client app, but can the client app handle the payload/url? like parsing the payload/url and go to specific page/screen identified in the url?

**Comment by luongnv89** [comment]
> Double checked and the full message successfully arrives using the official Dart example when called in the background and foreground. Could you please provide an MRE?

Hi @tschai-yim , I have created directly a MRE based on the client/master example app. Please check it here: https://github.com/cyber-geiger/toolbox-communicationApi/blob/mre/returning-control/dart/geiger_api/example/client_app/lib/main.dart

Steps to reproduce (please checkout this commit: [3f4159ba27329fcc8f0de3f3d8f6fcf31f3db045](https://github.com/cyber-geiger/toolbox-communicationApi/blob/3f4159ba27329fcc8f0de3f3d8f6fcf31f3db045/dart/geiger_api/example/client_app/lib/main.dart)):

1. Open the master app
2. Open the client app - make sure it has been connected with the master app
3. Comeback to the master app -> click "Call client in foreground"
4. The client app will be open and go to the `second-screen` - GOOD
5. On the `second-screen`, click on "Come back" to go back to the main screen (still on the client app)
6. Click on the button at the bottom of the screen "Update Received URL" => we should see the GeigerURL Value has been updated, this is the value which the client app have received from the master app in the step 3

Now everything work as expected until here.

8. Close/quit completely the client app
9. Open the master app -> Click "Call client in foreground"
10. The client app will be open, and we can see the "GeigerURL Value" has been updated, this is the value which the client app has received from the master app in the step 9 - different with previous value
11. The client app does not navigate to the 'second-screen' as expected

So here we can see that the client app has been woken up, received correctly the data sent by master app, but not able to navigate to the second-screen.

This problem can be avoided by checking the `GeigerURL Value` before building the main page as follow (I have tested and it worked, check the latest commit: [a740b6d961d535a306c1d93a7c965f0b6c29b1e5](https://github.com/cyber-geiger/toolbox-communicationApi/blob/a740b6d961d535a306c1d93a7c965f0b6c29b1e5/dart/geiger_api/example/client_app/lib/main.dart)),
```dart
class _HomePageState extends State<HomePage> {
  String receivedData =
      geigerURLValue; // To visualize the value of data sent from the master app
  @override
  Widget build(BuildContext context) {
    if (receivedData.isNotEmpty) {
      return SecondScreen();
    }
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
...
```

I am not sure if this is a good approach to resolve this problem. Any idea/feedback will be more than welcome here.

I will change the label, so it should not be a bug, but we should discuss to see if there is a better approach

**Comment by tschai-yim** [comment]
> > Tested on the official client / master example app. Both, payload and geiger url arrive on the client app.
> 
> * Did you check with the client app is off (not running in the background, but turn off completely)?
> * And also, the payload and the geiger url can arrive on the client app, but can the client app handle the payload/url? like parsing the payload/url and go to specific page/screen identified in the url?

Yes, I force-stopped it every time before testing it. The API processed the message and emitted it to the plugin listeners like normal. If after that point the message suddenly vanishes, it has nothing to do with GeigerAPI.

**Comment by tschai-yim** [comment]
Looked at your MRE and the problem was that `navigationKey` was still empty when the listener was called. You first have to inflate the UI before attaching the listener.
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  GeigerApi.masterExecutor = masterExecutor;
  api = (await getGeigerApi(pluginExecutor, pluginId))!;
  
  // navigatorKey still empty
  runApp(const App());
  // navigatorKey now set
  
  // Attach listeners AFTER initializing the UI
  api.registerListener(
      [MessageType.returningControl], returningControlListener);
  
  // Give back control to the event loop
  await api.registerPlugin();
  await api.activatePlugin();
}
```
The key insight here is that you **also need to move any await statements after the listener attachment**. Else you give back control to the event loop too early and let the API already process the message. 

We should perhaps add a constructor option to the GeigerApi which delays the message processing until `api.startMessageProcessing()` is called. Would that provide enough flexibility for you?

**Comment by luongnv89** [comment]
@tschai-yim Thanks for your detailed response.
Moving the UI initialisation before attaching the listener seems to be a good idea. I will try to adapt it in my app.

Regarding the delays option, it seems a good idea, could you plz try and test to see if it works well.

**Comment by luongnv89** [comment]
@tschai-yim for your information, I have made some changes based on your suggestion (build the UI before registering the listeners). It works well on my testing. So I think we can use this solution for now. If there is any other related problems pop up in the future, we can open a new issue.

If you have not started working on the delays yet, I think we can skip it for now. Otherwise you can continue and I am more than be willing to test the update.

Thank you very much for your help,
