### ISSUE TITLE
Typo error 

### ISSUE THREAD

**Issue by luongnv89** [cyber-geiger/toolbox-communicationApi#9]
It is not a bug, but just an error typo: `STORAGE_SUCESS` -> should be `STORAGE_SUCCESS`

https://github.com/cyber-geiger/toolbox-communicationApi/blob/6c38232e04614741b7e364f60bbc048d53b50410/lib/src/communication/message_type.dart#L73

**Comment by martingwerder** [comment]
Fixed as of now.
